{{- if .Values.secret.notificationURL -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "instagram-monitor.name" . }}-secrets
  labels:
    {{- include "instagram-monitor.labels" . | nindent 4 }}
type: Opaque
stringData:
  NOTIFICATION_URL: {{ .Values.secret.notificationURL | quote }}
{{- end }}
